---
### may need to change to get_url module        
- name: copy WebLogic Plugin Lib files
  copy:
    src: "{{ source_location_WL_Plugin_Lib }}"
    dest: "{{ dest_location_WL_Plugin_Lib }}"

    
- name: add export LD_LIBRARY_PATH=/opt/wlplugin/lib to .bash_profile
  lineinfile: 
    path: ~/.bash_profile
    line: 'export LD_LIBRARY_PATH={{ dest_location_WL_Plugin_Lib }}'
  
- name: add export LD_LIBRARY_PATH=/opt/wlplugin/lib to .bashrc
  lineinfile: 
    path: ~/.bashrc
    line: 'export LD_LIBRARY_PATH={{ dest_location_WL_Plugin_Lib }}'  